"""first migration

Revision ID: 3fbded418009
Revises: 
Create Date: 2021-10-11 18:10:50.544309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbded418009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    with op.batch_alter_table('blogtags', schema=None) as batch_op:
        batch_op.alter_column('blogid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tagid',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogtags', schema=None) as batch_op:
        batch_op.alter_column('tagid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('blogid',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
